const $=s=>document.querySelector(s), home=$('#home'), about=$('#about'), receivePage=$('#receivePage'), fileInput=$('#fileInput'), receiveInput=$('#receiveInput'), status=$('#status'), list=$('#fileList'), title=$('#statusTitle');
function showFiles(files,t){status.hidden=false;title.textContent=t;list.innerHTML='';[...files].forEach(f=>{const d=document.createElement('div');d.className='file';d.innerHTML='<span>'+f.name+'</span><small>'+((f.size/1048576).toFixed(2))+' MB</small>';list.appendChild(d)})}
$('#sendBtn').onclick=()=>fileInput.click();fileInput.onchange=async()=>{if(!fileInput.files.length)return;showFiles(fileInput.files,'Selected files');if(navigator.share){try{await navigator.share({title:'Android Auto File Transfer',files:[...fileInput.files]})}catch(e){}}};
let currentPairUrl='';function showPage(page){[home,about,receivePage].forEach(p=>{p.classList.remove('active');p.setAttribute('aria-hidden','true')});page.classList.add('active');page.setAttribute('aria-hidden','false');window.scrollTo(0,0)}function makeQr(){const box=$('#qrBox');box.innerHTML='';const token=(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));const u=new URL(location.href);u.searchParams.set('pair',token);u.hash='receive';currentPairUrl=u.href;const draw=()=>{if(window.QRCode){new QRCode(box,{text:currentPairUrl,width:240,height:240,colorDark:'#10152b',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});$('#qrStatus').textContent='QR ready • Scan with the sender phone';}else{$('#qrStatus').textContent='QR library did not load. Check internet and tap New QR.';box.innerHTML='<div class=qrFallback>QR unavailable<br>Use Copy link</div>';}};draw()}$('#receiveBtn').onclick=()=>{showPage(receivePage);makeQr()};$('#receiveBackBtn').onclick=()=>showPage(home);$('#refreshQrBtn').onclick=makeQr;$('#copyQrBtn').onclick=async()=>{try{await navigator.clipboard.writeText(currentPairUrl);$('#qrStatus').textContent='Pairing link copied.'}catch(e){prompt('Copy pairing link:',currentPairUrl)}};$('#shareQrBtn').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'Android Auto File Transfer pairing link',url:currentPairUrl})}catch(e){}}else{$('#copyQrBtn').click()}};receiveInput.onchange=()=>{if(receiveInput.files.length)showFiles(receiveInput.files,'Files selected')};
function openAbout(){showPage(about)}function goHome(){showPage(home)}
// Always start on Home; never restore About from a stale page state.
if(location.hash){history.replaceState(null,'',location.pathname+location.search)}goHome();if(new URLSearchParams(location.search).has('pair')){setTimeout(()=>{showPage(receivePage);makeQr()},150)}
$('#aboutBtn').onclick=openAbout;$('#backBtn').onclick=goHome;
async function shareApp(){const u=location.href;if(navigator.share){try{await navigator.share({title:'Android Auto File Transfer',text:'Simple and smart file transfer app',url:u})}catch(e){}}else{try{await navigator.clipboard.writeText(u);alert('App link copied!')}catch(e){prompt('Copy app link:',u)}}}$('#shareBtn').onclick=shareApp;$('#topShare').onclick=shareApp;
let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferred){await deferred.prompt();deferred=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=5').catch(()=>{}));

// Remove stale caches left by older builds after this version has loaded.
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>{rs.forEach(r=>{if(r.active && r.active.scriptURL.includes('sw.js')){} });});}
